### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'deprecated_since'

### ISSUE THREAD

**Issue by ryan-beisner** [trilioData/triliovault-cfg-scripts#101] opened 2018-09-26 13:45 UTC
The tvault-datamover-api system service is failing to start in a charm deployment:

```
ubuntu@juju-fe30ad-beisner-19:~$ systemctl status tvault-datamover-api.service
● tvault-datamover-api.service - Datamover API service
   Loaded: loaded (/etc/systemd/system/tvault-datamover-api.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Wed 2018-09-26 13:43:04 UTC; 1min 45s ago
  Process: 7989 ExecStart=/usr/bin/python /usr/bin/dmapi-api (code=exited, status=1/FAILURE)
 Main PID: 7989 (code=exited, status=1/FAILURE)

Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Unit entered failed state.
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Failed with result 'exit-code'.
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Service hold-off time over, scheduling restart.
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: Stopped Datamover API service.
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Start request repeated too quickly.
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: Failed to start Datamover API service.
```

```
Sep 26 13:43:02 juju-fe30ad-beisner-19 systemd[1]: Stopped Datamover API service.
Sep 26 13:43:02 juju-fe30ad-beisner-19 systemd[1]: Started Datamover API service.
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]: Traceback (most recent call last):
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]:   File "/usr/bin/dmapi-api", line 6, in <module>
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]:     from dmapi.cmd.api import main
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]:   File "/usr/lib/python2.7/dist-packages/dmapi/cmd/api.py", line 27, in <module>
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]:     import dmapi.conf
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]:   File "/usr/lib/python2.7/dist-packages/dmapi/conf/__init__.py", line 23, in <module>
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]:     from dmapi.conf import base
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]:   File "/usr/lib/python2.7/dist-packages/dmapi/conf/base.py", line 45, in <module>
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]:     """),
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]:   File "/usr/lib/python2.7/dist-packages/oslo_config/cfg.py", line 1081, in __init__
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]:     super(BoolOpt, self).__init__(name, type=types.Boolean(), **kwargs)
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7971]: TypeError: __init__() got an unexpected keyword argument 'deprecated_since'
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Unit entered failed state.
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Failed with result 'exit-code'.
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Service hold-off time over, scheduling restart.
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: Stopped Datamover API service.
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: Started Datamover API service.
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]: Traceback (most recent call last):
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]:   File "/usr/bin/dmapi-api", line 6, in <module>
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]:     from dmapi.cmd.api import main
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]:   File "/usr/lib/python2.7/dist-packages/dmapi/cmd/api.py", line 27, in <module>
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]:     import dmapi.conf
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]:   File "/usr/lib/python2.7/dist-packages/dmapi/conf/__init__.py", line 23, in <module>
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]:     from dmapi.conf import base
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]:   File "/usr/lib/python2.7/dist-packages/dmapi/conf/base.py", line 45, in <module>
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]:     """),
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]:   File "/usr/lib/python2.7/dist-packages/oslo_config/cfg.py", line 1081, in __init__
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]:     super(BoolOpt, self).__init__(name, type=types.Boolean(), **kwargs)
Sep 26 13:43:03 juju-fe30ad-beisner-19 python[7983]: TypeError: __init__() got an unexpected keyword argument 'deprecated_since'
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Unit entered failed state.
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Failed with result 'exit-code'.
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Service hold-off time over, scheduling restart.
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: Stopped Datamover API service.
Sep 26 13:43:03 juju-fe30ad-beisner-19 systemd[1]: Started Datamover API service.
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]: Traceback (most recent call last):
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]:   File "/usr/bin/dmapi-api", line 6, in <module>
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]:     from dmapi.cmd.api import main
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]:   File "/usr/lib/python2.7/dist-packages/dmapi/cmd/api.py", line 27, in <module>
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]:     import dmapi.conf
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]:   File "/usr/lib/python2.7/dist-packages/dmapi/conf/__init__.py", line 23, in <module>
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]:     from dmapi.conf import base
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]:   File "/usr/lib/python2.7/dist-packages/dmapi/conf/base.py", line 45, in <module>
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]:     """),
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]:   File "/usr/lib/python2.7/dist-packages/oslo_config/cfg.py", line 1081, in __init__
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]:     super(BoolOpt, self).__init__(name, type=types.Boolean(), **kwargs)
Sep 26 13:43:04 juju-fe30ad-beisner-19 python[7989]: TypeError: __init__() got an unexpected keyword argument 'deprecated_since'
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Main process exited, code=exited, status=1/FAILURE
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Unit entered failed state.
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Failed with result 'exit-code'.
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Service hold-off time over, scheduling restart.
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: Stopped Datamover API service.
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: tvault-datamover-api.service: Start request repeated too quickly.
Sep 26 13:43:04 juju-fe30ad-beisner-19 systemd[1]: Failed to start Datamover API service.
```

```
Model    Controller           Cloud/Region             Version    SLA          Timestamp
beisner  beisner-serverstack  serverstack/serverstack  2.5-beta1  unsupported  13:43:50Z

App                    Version       Status   Scale  Charm                  Store       Rev  OS      Charm version  Notes
ceph-mon               12.2.4        active       3  ceph-mon               jujucharms   23  ubuntu
ceph-osd               12.2.4        active       3  ceph-osd               jujucharms  257  ubuntu
ceph-radosgw           12.2.4        active       1  ceph-radosgw           jujucharms  256  ubuntu
cinder                 12.0.3        active       1  cinder                 jujucharms  268  ubuntu
cinder-ceph            12.0.3        active       1  cinder-ceph            jujucharms  231  ubuntu
glance                 16.0.1        active       1  glance                 jujucharms  263  ubuntu
keystone               13.0.0        active       1  keystone               jujucharms  379  ubuntu
mysql                  5.6.37-26.21  active       1  percona-cluster        jujucharms  259  ubuntu
neutron-api            12.0.3        active       1  neutron-api            jujucharms  258  ubuntu
neutron-gateway        8.4.0         active       1  neutron-gateway        jujucharms  247  ubuntu
neutron-openvswitch    12.0.3        active       3  neutron-openvswitch    jujucharms  249  ubuntu
nova-cloud-controller  17.0.5        active       1  nova-cloud-controller  jujucharms  306  ubuntu
nova-compute           17.0.5        active       3  nova-compute           jujucharms  282  ubuntu
ntp                    4.2.8p4+dfsg  active       4  ntp                    jujucharms   24  ubuntu
openstack-dashboard    13.0.1        active       1  openstack-dashboard    jujucharms  257  ubuntu
rabbitmq-server        3.6.10        active       1  rabbitmq-server        jujucharms   72  ubuntu
trilio-data-mover                    blocked      3  trilio-data-mover      local         0  ubuntu
trilio-dm-api          13.1.4        blocked      1  trilio-dm-api          local         1  ubuntu
trilio-horizon-plugin  3.1.28        active       1  trilio-horizon-plugin  local         0  ubuntu

Unit                        Workload  Agent  Machine  Public address  Ports              Message
ceph-mon/0                  active    idle   0        10.5.0.11                          Unit is ready and clustered
ceph-mon/1*                 active    idle   1        10.5.0.7                           Unit is ready and clustered
ceph-mon/2                  active    idle   2        10.5.0.12                          Unit is ready and clustered
ceph-osd/0                  active    idle   3        10.5.0.31                          Unit is ready (1 OSD)
ceph-osd/1                  active    idle   4        10.5.0.21                          Unit is ready (1 OSD)
ceph-osd/2*                 active    idle   5        10.5.0.25                          Unit is ready (1 OSD)
ceph-radosgw/0*             active    idle   6        10.5.0.14       80/tcp             Unit is ready
cinder/0*                   active    idle   7        10.5.0.26       8776/tcp           Unit is ready
  cinder-ceph/0*            active    idle            10.5.0.26                          Unit is ready
glance/0*                   active    idle   8        10.5.0.5        9292/tcp           Unit is ready
keystone/0*                 active    idle   9        10.5.0.24       5000/tcp           Unit is ready
mysql/0*                    active    idle   10       10.5.0.22       3306/tcp           Unit is ready
neutron-api/0*              active    idle   11       10.5.0.8        9696/tcp           Unit is ready
neutron-gateway/1*          active    idle   20       10.5.0.17                          Unit is ready
  ntp/4                     active    idle            10.5.0.17       123/udp            Ready
nova-cloud-controller/0*    active    idle   13       10.5.0.10       8774/tcp,8778/tcp  Unit is ready
nova-compute/0              active    idle   14       10.5.0.13                          Unit is ready
  neutron-openvswitch/0*    active    idle            10.5.0.13                          Unit is ready
  ntp/0*                    active    idle            10.5.0.13       123/udp            Ready
  trilio-data-mover/0*      blocked   idle            10.5.0.13                          Invalid Backup target type, please provide valid info
nova-compute/1*             active    idle   15       10.5.0.16                          Unit is ready
  neutron-openvswitch/1     active    idle            10.5.0.16                          Unit is ready
  ntp/1                     active    idle            10.5.0.16       123/udp            Ready
  trilio-data-mover/1       blocked   idle            10.5.0.16                          Invalid Backup target type, please provide valid info
nova-compute/2              active    idle   16       10.5.0.19                          Unit is ready
  neutron-openvswitch/2     active    idle            10.5.0.19                          Unit is ready
  ntp/2                     active    idle            10.5.0.19       123/udp            Ready
  trilio-data-mover/2       blocked   idle            10.5.0.19                          Invalid Backup target type, please provide valid info
openstack-dashboard/0*      active    idle   17       10.5.0.3        80/tcp,443/tcp     Unit is ready
  trilio-horizon-plugin/0*  active    idle            10.5.0.3                           Ready...
rabbitmq-server/0*          active    idle   18       10.5.0.20       5672/tcp           Unit is ready
trilio-dm-api/0*            blocked   idle   19       10.5.0.15       8784/tcp           Services not running that should be: tvault-datamover-api
```

**Comment by abhijeetpatra** [comment] 2018-10-02 12:07
This issue could be because of mismatch of the appliance build and the charm-scripts. We could not reproduce this issue with latest build.
Closing this issue.

**Closed by abhijeetpatra** 2018-10-02 12:07 UTC
